name: Build QMK firmware
on:
  pull_request:
  push:
    branches:
      - main
      - master
      - 'develop**'
      - github-actions-build
jobs:
  gather-keyboards:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.repository}}
        ref: ${{ github.ref }}
    - id: set-matrix
      run: |
          content=$(bash bin/fp_build.sh -l | sed s~keyboards/fingerpunch/~~| grep ffkb/rp/v1 | jq -Rsc '. / "\n" - [""]')
          content="{\"keyboard\":$content}"
          echo "::set-output name=matrix::$content"

  Build:
    needs: gather-keyboards
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.gather-keyboards.outputs.matrix)}}
    steps:
      - name: Checkout QMK
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository}}
          ref: ${{ github.ref }}
          submodules: recursive

      - name: Build firmware
        shell: bash
        run: |
          make fingerpunch/ffkb/rp/v1:hrm FP_TRACKBALL_ENABLE=yes FP_EC11=yes AUDIO_ENABLE=no HAPTIC_ENABLE=no

      - name: Archive firmware
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: qmk_fingerpunch_${{ github.actor }}
          path: |
            *.hex
            *.bin
            *.uf2

